export enum QuizActionTypes {
  ADD_QUIZ_DATA = "ADD_QUIZ_DATA ",
  UPDATE_QUIZ_DATA = "UPDATE_QUIZ_DATA ",
  REMOVE_QUIZ_DATA = "REMOVE_QUIZ_DATA ",
  SET_SELECTED_QUIZ = "SET_SELECTED_QUIZ ",

  ADD_QUIZ_QUESTION = "ADD_QUIZ_QUESTION",
  UPDATE_QUIZ_QUESTION = "UPDATE_QUIZ_QUESTION",
  REMOVE_QUIZ_QUESTION = "REMOVE_QUIZ_QUESTION",
  SET_SELECTED_QUIZ_QUESTION = "SET_SELECTED_QUIZ_QUESTION",

  ADD_QUIZ_QUESTION_ANSWER = "ADD_QUIZ_QUESTION_ANSWER",
  UPDATE_QUIZ_QUESTION_ANSWER = "UPDATE_QUIZ_QUESTION_ANSWER ",
  REMOVE_QUIZ_QUESTION_ANSWER = "REMOVE_QUIZ_QUESTION_ANSWER "
}
